{% set name = "pyepics" %}
{% set version = "3.4.1" %}
{% set sha256 = "a995685638c01a9326d3414de9b5471fb7b0bf6b1c60de1efae778c25dedaabf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   url: https://github.com/pyepics/{{ name }}/archive/{{ version }}.tar.gz
   sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [py<36]

requirements:
  host:
      - python
      - pip
  run:
      - python
      # pkg_resources used in epics/ca.py
      - setuptools
      - epics-base
      - numpy
      - pyparsing

test:
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices
  commands:
    - python -c "import epics; epics.ca.find_libca()"

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open
  summary: Python interface to Epics Channel Access
  license_file: LICENSE
  dev_url: https://github.com/pyepics/pyepics
  doc_url: http://pyepics.github.io/pyepics
