{% set name = "pyepics" %}
{% set version = "3.4.0" %}
{% set sha256 = "a2913ee5fdab9dfb3d50c0ccb83f7129902e6fdc7ce9c4c1cc9d0d4b2f9c0438" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://github.com/pyepics/{{ name }}/archive/{{ version }}.tar.gz
   sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True # [py<36]
  patches:
      - libca.patch
requirements:
  build:
      - python
      - setuptools
      - numpy
      - pyparsing

  run:
      - python
      - setuptools
      - numpy
      - pyparsing

test:
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open
  summary: Python interface to Epics Channel Access
  # https://github.com/pyepics/pyepics/pull/108
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  dev_url: https://github.com/pyepics/pyepics
  doc_url: http://pyepics.github.io/pyepics

extra:
  recipe-maintainers:
    - CJ-Wright
    - jrmlhermitte
    - stuartcampbell
    - mrakitin
    - hhslepicka
