{% set name = "pyepics" %}
{% set version = "3.4.2" %}
{% set sha256 = "673fc8f6c8a2663c15473938fd3b55c2d3431dc739aa479b6d9d005373219068" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
      # pkg_resources used in epics/ca.py
    - setuptools
    - epics-base
    - numpy
    - pyparsing

test:
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices
  commands:
    - python -c "import epics; epics.ca.find_libca()"

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open
  license_file: LICENSE
  summary: Python interface to Epics Channel Access
  dev_url: https://github.com/pyepics/pyepics
  doc_url: http://pyepics.github.io/pyepics
