{% set name = "pyepics" %}
{% set version = "3.3.0" %}
{% set sha256 = "30e3be02436dc27eb2e485a67e334ae4ff35e94cc29427a9887ed1ab82cc014e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
   sha256: {{ sha256 }}

build:
  number: 1
  skip: True # [py<36]
  script: |
    export PYEPICS_LIBCA=$PREFIX/lib/libca.so  # [not win]
    export NOLIBCA=1  # [not win]
    echo "Using LIBCA from $PYEPICS_LIBCA"  # [not win]
    python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - epics-base
    - setuptools
  run:
    - python
    - epics-base
    - numpy
    - pyparsing
    - setuptools  # needed to import pkg_resources

test:
  imports:
  - epics
  - epics.autosave
  - epics.compat
  - epics.devices

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open
  summary: Python interface to Epics Channel Access
  # https://github.com/pyepics/pyepics/pull/108
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  dev_url: https://github.com/pyepics/pyepics
  doc_url: http://pyepics.github.io/pyepics
